// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseModel } from "./BaseModel";
import type { RecProcessingMode } from "./RecProcessingMode";
import type { RecResizeFilter } from "./RecResizeFilter";

export type PaddleRecCrnn = { baseModel: BaseModel, dictPath: string | null, resizeFilter: RecResizeFilter, processingMode: RecProcessingMode, microBatchSize: number, widthBucketStep: number, };
